name: Deploy Ptolemies Status System to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "get_status.py"
      - "status"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate fresh status JSON
        run: |
          python get_status.py --save docs/status.json
          echo "✅ Status JSON generated"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
